CREATE TABLE IF NOT EXISTS users (
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    login    INTEGER NOT NULL,
    name     VARCHAR(255),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200),
    release_date DATE,
    duration     INTEGER,
    rating_id    INTEGER
);

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS rating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL
);

ALTER TABLE films
    ADD FOREIGN KEY (rating_id) REFERENCES rating;

CREATE TABLE IF NOT EXISTS film_genres (
    film_id INTEGER NOT NULL
        REFERENCES films,
    id INTEGER NOT NULL
        REFERENCES genres,
    PRIMARY KEY (film_id, id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id INTEGER NOT NULL
        REFERENCES films,
    user_id INTEGER NOT NULL
        REFERENCES users,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user_id INTEGER NOT NULL
        REFERENCES users,
    friend_id INTEGER NOT NULL
        REFERENCES users,
    PRIMARY KEY (user_id, friend_id)
);